CREATE TABLE IF NOT EXISTS PRODUTOS (
	ID_PRODUTO		INT PRIMARY KEY AUTO_INCREMENT	,
    IMAGEM			VARCHAR(255)					,
    CD_PRODUTO		CHAR(4) NOT NULL UNIQUE			,
    DS_PRODUTO		VARCHAR(100) NOT NULL			,
    VL_PRODUTO		FLOAT NOT NULL					,
    QUANTIDADE		INT NOT NULL					,
    OBSERVACOES		TEXT							,
    ATIVO			BOOLEAN							);